BUNDLE_NAME = DataLogoSwitcher
DataLogoSwitcher_FILES = DataLogoSwitcher.m
DataLogoSwitcher_INSTALL_PATH = /Library/PreferenceBundles
DataLogoSwitcher_FRAMEWORKS = UIKit
DataLogoSwitcher_CFLAGS = -fobjc-arc
DataLogoSwitcher_PRIVATE_FRAMEWORKS = Preferences

SDKVERSION = 9.2
SYSROOT = $(THEOS)/sdks/iPhoneOS9.2.sdk
ARCHS = armv7 armv7s arm64 arm64e
TARGET = iphone:clang::5.0

GO_EASY_ON_ME = 1

include theos/makefiles/common.mk
include $(THEOS_MAKE_PATH)/bundle.mk